apiVersion: v1
kind: Template
metadata:
  name: springboot-echo-service
parameters:
- name: APP_NAME
  displayName: Application Name
  required: true
  value: springboot-echo-service
- name: GIT_URL
  displayName: Source URL
  required: true
  value: https://github.com/nathansevugan/springboot-echo-service.git
- name: GIT_REF
  displayName: Source Ref
  required: true
  value: master
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: codecentric-springboot
  spec:
#    tags:
#    - annotations:
#        supports: java
#        tags: java
#        version: "1.8.0"
      from:
        kind: DockerImage
        name: codecentric/springboot-maven3-centos:latest
#      name: "1.4.0"
#    - annotations:
#        supports: java
#        tags: builder,java
#      from:
#        kind:
#        name: "1.4.0"
      name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: springboot-echo-service
    name: springboot-echo-service
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: springboot-echo-service:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/nathansevugan/springboot-echo-service.git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: ./jenkinsfile.groovy
        env:
          - name: "APP_NAME"
            value: ${APP_NAME}
          - name: "GIT_REF"
            value: ${GIT_SOURCE_REF}
          - name: "GIT_REPOSITORY"
            value: ${GIT_SOURCE_URL}
          - name: "GIT_CREDENTIALS"
            value: ${GIT_SOURCE_SECRET}
      successfulBuildsHistoryLimit: 5
      triggers:
        type: ImageChange

